### ISSUE TITLE
App crash in IOS after upgrade to 0.3.3

### ISSUE THREAD

**Issue by DjaberDribine** [YoussefKababe/admob_flutter#74]
** BUILD FAILED **
Xcode's output:
↳
...../flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.3/ios/Classes/AdmobBanner.swift:76:43: error: value of type 'GADRequestConfiguration' has no member 'testDeviceIdentifiers'
                GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [kGADSimulatorID as! String]
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~
  ......./flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.3/ios/Classes/AdmobInterstitialPlugin.swift:83:39: error: value of type 'GADRequestConfiguration' has no member 'testDeviceIdentifiers'
            GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [kGADSimulatorID as! String]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~
    ......./flutter/.pub-cache/hosted/pub.dartlang.org/admob_flutter-0.3.3/ios/Classes/AdmobRewardPlugin.swift:90:39: error: value of type 'GADRequestConfiguration' has no member 'testDeviceIdentifiers'
            GADMobileAds.sharedInstance().requestConfiguration.testDeviceIdentifiers = [kGADSimulatorID as! String]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~ ~~~~~~~~~~~~~~~~~~~~~

Could not build the application for the simulator.
Error launching application on iPhone Xʀ.


How to fix this ??

**Comment by EliasDeuss** [comment]
Does it also give you that error for Android @DjaberDribine ? Hey @kmcgill88 can you look into this.

**Comment by DjaberDribine** [comment]
@EliasDeuss only for IOS

**Comment by gildaswise** [comment]
You need to update Xcode to 11, this was a required change starting on iOS 13.

**Comment by DjaberDribine** [comment]
@gildaswise don't working even with Xcode 11

**Comment by craig006** [comment]
@gildaswise @DjaberDribine I'm also facing this exact issue. On xcode 11.

Any fixes yet?

**Comment by gildaswise** [comment]
Is it a crash or the app just doesn't build? Did you run both `pod install` and `pod update` on the `ios` folder? I made this change because the previous way didn't work at all, and [this was the recommendation](https://stackoverflow.com/questions/58000287/identify-the-test-device-for-admob).

**Comment by DjaberDribine** [comment]
@gildaswise @craig006 fixed after pod install and pod update.
thx @gildaswise
